In [81]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
#from imblearn.over_sampling import SMOTE,RandomOverSampler
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
df["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

# Model Training

In [4]:
x = df.drop("target",axis=1) 
y = df["target"]
# x
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45,stratify=y)

# Model selection

# HyperParameterTunning DT

In [5]:
dt_clf = DecisionTreeClassifier()
hyper_paramter = {"criterion":['gini',"entropy"],
                "max_depth":np.arange(10,60),
                 "min_samples_split":np.arange(3,60),
                 "min_samples_leaf":np.arange(1,12),
                 "random_state":[42,43,45,46]}
rscv_dt = RandomizedSearchCV(dt_clf,hyper_paramter,cv=5)
rscv_dt.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
                                        'min_samples_leaf': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
                                        'min_samples_split': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59]),
                                        'random_state': [42, 43, 45, 46]})

In [6]:
rscv_dt.best_estimator_

DecisionTreeClassifier(max_depth=37, min_samples_leaf=9, min_samples_split=15,
                       random_state=43)

# 1.DecisionTree

In [7]:
dt_clf = DecisionTreeClassifier(max_depth=23, min_samples_leaf=4, min_samples_split=9,
                       random_state=42)
dt_clf.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=23, min_samples_leaf=4, min_samples_split=9,
                       random_state=42)

## Evalution

### Training

In [8]:
y_pred_train = dt_clf.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_train,y_pred_train)
print("accuracy",accuracy)
clf_report = classification_report(y_train,y_pred_train)
print("clf_report\n",clf_report)

confusion metrics
 [[101   9]
 [ 15 117]]
accuracy 0.9008264462809917
clf_report
               precision    recall  f1-score   support

           0       0.87      0.92      0.89       110
           1       0.93      0.89      0.91       132

    accuracy                           0.90       242
   macro avg       0.90      0.90      0.90       242
weighted avg       0.90      0.90      0.90       242



### Testing

In [9]:
y_pred_test = dt_clf.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_test,y_pred_test)
print("accuracy",accuracy)
clf_report = classification_report(y_test,y_pred_test)
print("clf_report\n",clf_report)

confusion metrics
 [[19  9]
 [ 7 26]]
accuracy 0.7377049180327869
clf_report
               precision    recall  f1-score   support

           0       0.73      0.68      0.70        28
           1       0.74      0.79      0.76        33

    accuracy                           0.74        61
   macro avg       0.74      0.73      0.73        61
weighted avg       0.74      0.74      0.74        61



# Pruning

In [10]:
d_tree_model = DecisionTreeClassifier(random_state=49,ccp_alpha=0.0)
d_tree_model.fit(x_train,y_train)

DecisionTreeClassifier(random_state=49)

# Evaluation

### Training

In [11]:

y_pred_train = dt_clf.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_train,y_pred_train)
print("accuracy",accuracy)
clf_report = classification_report(y_train,y_pred_train)
print("clf_report\n",clf_report)

confusion metrics
 [[101   9]
 [ 15 117]]
accuracy 0.9008264462809917
clf_report
               precision    recall  f1-score   support

           0       0.87      0.92      0.89       110
           1       0.93      0.89      0.91       132

    accuracy                           0.90       242
   macro avg       0.90      0.90      0.90       242
weighted avg       0.90      0.90      0.90       242



### Testing

In [53]:
y_pred_test = dt_clf.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_test,y_pred_test)
print("accuracy",accuracy)
clf_report = classification_report(y_test,y_pred_test)
print("clf_report\n",clf_report)

confusion metrics
 [[19  9]
 [ 7 26]]
accuracy 0.7377049180327869
clf_report
               precision    recall  f1-score   support

           0       0.73      0.68      0.70        28
           1       0.74      0.79      0.76        33

    accuracy                           0.74        61
   macro avg       0.74      0.73      0.73        61
weighted avg       0.74      0.74      0.74        61



# Post_Prunning

In [12]:
dict_result = d_tree_model.cost_complexity_pruning_path(x_train,y_train)
ccp_alphas_list = dict_result["ccp_alphas"]
ccp_alphas_list

array([0.        , 0.00385675, 0.00404431, 0.00407056, 0.0050632 ,
       0.00522877, 0.00550964, 0.00661157, 0.00688705, 0.00688705,
       0.0072314 , 0.00768603, 0.00782949, 0.00991736, 0.00991736,
       0.01056015, 0.01114265, 0.01115702, 0.01126972, 0.01398368,
       0.01496458, 0.02568847, 0.0377135 , 0.04855589, 0.1419503 ])

In [14]:
train_accuracy_list = []
test_accuracy_list = []
for ccp_alpha_v in ccp_alphas_list:
    dt_clf_1 = DecisionTreeClassifier(random_state=45,ccp_alpha=ccp_alpha_v)
    dt_clf_1.fit(x_train,y_train)
    
    train_accuracy_list.append(dt_clf_1.score(x_train,y_train))
    test_accuracy_list.append(dt_clf_1.score(x_test,y_test))
train_accuracy_list

[1.0,
 0.9958677685950413,
 0.9917355371900827,
 0.987603305785124,
 0.9793388429752066,
 0.9710743801652892,
 0.9628099173553719,
 0.9586776859504132,
 0.9504132231404959,
 0.9504132231404959,
 0.9462809917355371,
 0.9380165289256198,
 0.9338842975206612,
 0.9256198347107438,
 0.9132231404958677,
 0.8884297520661157,
 0.8884297520661157,
 0.8842975206611571,
 0.8636363636363636,
 0.859504132231405,
 0.8347107438016529,
 0.8347107438016529,
 0.7768595041322314,
 0.768595041322314,
 0.5454545454545454]

In [15]:
test_accuracy_list

[0.7213114754098361,
 0.7213114754098361,
 0.7213114754098361,
 0.7213114754098361,
 0.7049180327868853,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7377049180327869,
 0.7540983606557377,
 0.7540983606557377,
 0.7704918032786885,
 0.7704918032786885,
 0.7868852459016393,
 0.7868852459016393,
 0.7868852459016393,
 0.7377049180327869,
 0.7213114754098361,
 0.5409836065573771]

In [16]:
np.where(test_accuracy_list == np.max(test_accuracy_list))

(array([19, 20, 21], dtype=int64),)

In [17]:
test_accuracy_list[21]

0.7868852459016393

In [18]:
train_accuracy_list[21]

0.8347107438016529

# 2. RandomForest

In [19]:
rf_clf = RandomForestClassifier()
rf_clf.fit(x_train,y_train)

RandomForestClassifier()

## Evalution

### Training 

In [20]:
y_pred_train = rf_clf.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_train,y_pred_train)
print("accuracy",accuracy)
clf_report = classification_report(y_train,y_pred_train)
print("clf_report\n",clf_report)

confusion metrics
 [[110   0]
 [  0 132]]
accuracy 1.0
clf_report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       110
           1       1.00      1.00      1.00       132

    accuracy                           1.00       242
   macro avg       1.00      1.00      1.00       242
weighted avg       1.00      1.00      1.00       242



## Testing

In [21]:
y_pred_test = rf_clf.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_test,y_pred_test)
print("accuracy",accuracy)
clf_report = classification_report(y_test,y_pred_test)
print("clf_report\n",clf_report)

confusion metrics
 [[17 11]
 [ 2 31]]
accuracy 0.7868852459016393
clf_report
               precision    recall  f1-score   support

           0       0.89      0.61      0.72        28
           1       0.74      0.94      0.83        33

    accuracy                           0.79        61
   macro avg       0.82      0.77      0.78        61
weighted avg       0.81      0.79      0.78        61



# HperParameterTunning RF

In [44]:
rf_clf1 = RandomForestClassifier()
hyper_paramter = {"n_estimators":np.arange(10,20),
                  "criterion":['gini',"entropy"],
                "max_depth":np.arange(10,60),
                 "min_samples_split":np.arange(3,60),
                 "min_samples_leaf":np.arange(1,12),
                 "random_state":[42,43,45,46],
                 "oob_score":[True]}
rscv_rf = RandomizedSearchCV(rf_clf1,hyper_paramter,cv=5)
rscv_rf.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
                                        'min_samples_leaf': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
                                        'min_samples_split': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59]),
                                        'n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                                        'oob_score':

In [45]:
rscv_rf.best_estimator_

RandomForestClassifier(max_depth=31, min_samples_split=40, n_estimators=14,
                       oob_score=True, random_state=43)

In [47]:
rf_clf1 =RandomForestClassifier(max_depth=31, min_samples_split=40, n_estimators=14,
                       oob_score=True, random_state=43)

In [49]:
rf_clf1.fit(x_train,y_train)

RandomForestClassifier(max_depth=31, min_samples_split=40, n_estimators=14,
                       oob_score=True, random_state=43)

### traing

In [50]:
y_pred_train = rf_clf1.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_train,y_pred_train)
print("accuracy",accuracy)
clf_report = classification_report(y_train,y_pred_train)
print("clf_report\n",clf_report)

confusion metrics
 [[ 93  17]
 [ 12 120]]
accuracy 0.8801652892561983
clf_report
               precision    recall  f1-score   support

           0       0.89      0.85      0.87       110
           1       0.88      0.91      0.89       132

    accuracy                           0.88       242
   macro avg       0.88      0.88      0.88       242
weighted avg       0.88      0.88      0.88       242



In [51]:
y_pred_test = rf_clf1.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_test,y_pred_test)
print("accuracy",accuracy)
clf_report = classification_report(y_test,y_pred_test)
print("clf_report\n",clf_report)

confusion metrics
 [[17 11]
 [ 2 31]]
accuracy 0.7868852459016393
clf_report
               precision    recall  f1-score   support

           0       0.89      0.61      0.72        28
           1       0.74      0.94      0.83        33

    accuracy                           0.79        61
   macro avg       0.82      0.77      0.78        61
weighted avg       0.81      0.79      0.78        61



# ADA

In [87]:
adb_clf= AdaBoostClassifier()
adb_clf.fit(x_train,y_train)

AdaBoostClassifier()

## Evalution

### Training

In [88]:
y_pred_train = adb_clf.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_train,y_pred_train)
print("accuracy",accuracy)
clf_report = classification_report(y_train,y_pred_train)
print("clf_report\n",clf_report)

confusion metrics
 [[105   5]
 [  7 125]]
accuracy 0.9504132231404959
clf_report
               precision    recall  f1-score   support

           0       0.94      0.95      0.95       110
           1       0.96      0.95      0.95       132

    accuracy                           0.95       242
   macro avg       0.95      0.95      0.95       242
weighted avg       0.95      0.95      0.95       242



### Testing

In [89]:
y_pred_test = adb_clf.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_test,y_pred_test)
print("accuracy",accuracy)
clf_report = classification_report(y_test,y_pred_test)
print("clf_report\n",clf_report)

confusion metrics
 [[16 12]
 [ 4 29]]
accuracy 0.7377049180327869
clf_report
               precision    recall  f1-score   support

           0       0.80      0.57      0.67        28
           1       0.71      0.88      0.78        33

    accuracy                           0.74        61
   macro avg       0.75      0.73      0.73        61
weighted avg       0.75      0.74      0.73        61



# HyperParameterTunning ADA

In [52]:
adb_clf1 = AdaBoostClassifier()
hyper_paramter = {"n_estimators":np.arange(10,60),
                 "learning_rate":np.arange(0,4,0.001)}
rscv_adb = RandomizedSearchCV(adb_clf1,hyper_paramter,cv=5)
rscv_adb.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=AdaBoostClassifier(),
                   param_distributions={'learning_rate': array([0.000e+00, 1.000e-03, 2.000e-03, ..., 3.997e+00, 3.998e+00,
       3.999e+00]),
                                        'n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])})

In [54]:
rscv_adb.best_estimator_


AdaBoostClassifier(learning_rate=0.307, n_estimators=11)

In [56]:
adb_clf1 =AdaBoostClassifier(learning_rate=0.307, n_estimators=11)
adb_clf1.fit(x_train,y_train)

AdaBoostClassifier(learning_rate=0.307, n_estimators=11)

In [57]:
y_pred_train = adb_clf1.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_train,y_pred_train)
print("accuracy",accuracy)
clf_report = classification_report(y_train,y_pred_train)
print("clf_report\n",clf_report)

confusion metrics
 [[ 86  24]
 [ 11 121]]
accuracy 0.8553719008264463
clf_report
               precision    recall  f1-score   support

           0       0.89      0.78      0.83       110
           1       0.83      0.92      0.87       132

    accuracy                           0.86       242
   macro avg       0.86      0.85      0.85       242
weighted avg       0.86      0.86      0.85       242



In [58]:
y_pred_test = adb_clf1.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)

accuracy = accuracy_score(y_test,y_pred_test)
print("accuracy",accuracy)
clf_report = classification_report(y_test,y_pred_test)
print("clf_report\n",clf_report)

confusion metrics
 [[16 12]
 [ 3 30]]
accuracy 0.7540983606557377
clf_report
               precision    recall  f1-score   support

           0       0.84      0.57      0.68        28
           1       0.71      0.91      0.80        33

    accuracy                           0.75        61
   macro avg       0.78      0.74      0.74        61
weighted avg       0.77      0.75      0.75        61



# 4. KNN with hyperParameter 

## 1.GridSearchCv

In [61]:
knn_clf = KNeighborsClassifier()
hyperparameter = {"n_neighbors":np.arange(2,20),
                 "p":[1,2]}
gscv_knn_clf = GridSearchCV(knn_clf,hyperparameter,cv=5)
gscv_knn_clf.fit(x_train,y_train)
gscv_knn_clf.best_estimator_

KNeighborsClassifier(p=1)

In [62]:
gscv_knn_clf.best_params_

{'n_neighbors': 5, 'p': 1}

In [63]:
knn_clf = KNeighborsClassifier(p=1)
knn_clf.fit(x_train,y_train)

KNeighborsClassifier(p=1)

# evaluation

### Training

In [64]:
y_pred_train = knn_clf.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)
print("*"*20)
accuracy = accuracy_score(y_train,y_pred_train)
print("Accuracy\n",accuracy)
print("*"*20)
clf_report = classification_report(y_train,y_pred_train)
print("classification report\n",clf_report)

confusion metrics
 [[ 88  22]
 [ 21 111]]
********************
Accuracy
 0.8223140495867769
********************
classification report
               precision    recall  f1-score   support

           0       0.81      0.80      0.80       110
           1       0.83      0.84      0.84       132

    accuracy                           0.82       242
   macro avg       0.82      0.82      0.82       242
weighted avg       0.82      0.82      0.82       242



### Testing

In [65]:
y_pred_test = knn_clf.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)
print("*"*20)
accuracy = accuracy_score(y_test,y_pred_test)
print("Accuracy\n",accuracy)
print("*"*20)
clf_report = classification_report(y_test,y_pred_test)
print("classification report\n",clf_report)

confusion metrics
 [[14 14]
 [ 4 29]]
********************
Accuracy
 0.7049180327868853
********************
classification report
               precision    recall  f1-score   support

           0       0.78      0.50      0.61        28
           1       0.67      0.88      0.76        33

    accuracy                           0.70        61
   macro avg       0.73      0.69      0.69        61
weighted avg       0.72      0.70      0.69        61



## 2. RandomisedSearchCv

In [76]:
knn_clf1 = KNeighborsClassifier()
hyperparameter = {"n_neighbors":np.arange(3,40),
                 "p":[1,2]}
rscv_knn_clf1 = RandomizedSearchCV(knn_clf,hyperparameter,cv=5)
rscv_knn_clf1.fit(x_train,y_train)
rscv_knn_clf1.best_estimator_

KNeighborsClassifier(n_neighbors=28, p=1)

In [77]:
knn_clf1 = KNeighborsClassifier(n_neighbors=28, p=1)
knn_clf1.fit(x_train,y_train)


KNeighborsClassifier(n_neighbors=28, p=1)

## Evaluation

### 1.Training

In [78]:

y_pred_train = knn_clf1.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)
print("*"*20)
accuracy = accuracy_score(y_train,y_pred_train)
print("Accuracy\n",accuracy)
print("*"*20)
clf_report = classification_report(y_train,y_pred_train)
print("classification report\n",clf_report)

confusion metrics
 [[ 72  38]
 [ 27 105]]
********************
Accuracy
 0.731404958677686
********************
classification report
               precision    recall  f1-score   support

           0       0.73      0.65      0.69       110
           1       0.73      0.80      0.76       132

    accuracy                           0.73       242
   macro avg       0.73      0.72      0.73       242
weighted avg       0.73      0.73      0.73       242



### 2.Testing

In [79]:

y_pred_test = knn_clf.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)
print("*"*20)
accuracy = accuracy_score(y_test,y_pred_test)
print("Accuracy\n",accuracy)
print("*"*20)
clf_report = classification_report(y_test,y_pred_test)
print("classification report\n",clf_report)

confusion metrics
 [[14 14]
 [ 4 29]]
********************
Accuracy
 0.7049180327868853
********************
classification report
               precision    recall  f1-score   support

           0       0.78      0.50      0.61        28
           1       0.67      0.88      0.76        33

    accuracy                           0.70        61
   macro avg       0.73      0.69      0.69        61
weighted avg       0.72      0.70      0.69        61



# 5.Logistic Regrassion

In [82]:
lr_model= LogisticRegression()
lr_model.fit(x_train,y_train)

LogisticRegression()

## Evalution

### Training

In [84]:

y_pred_train = lr_model.predict(x_train)

cnf_metrics = confusion_matrix(y_train,y_pred_train)
print("confusion metrics\n",cnf_metrics)
print("*"*20)
accuracy = accuracy_score(y_train,y_pred_train)
print("Accuracy\n",accuracy)
print("*"*20)
clf_report = classification_report(y_train,y_pred_train)
print("classification report\n",clf_report)

confusion metrics
 [[ 88  22]
 [  9 123]]
********************
Accuracy
 0.871900826446281
********************
classification report
               precision    recall  f1-score   support

           0       0.91      0.80      0.85       110
           1       0.85      0.93      0.89       132

    accuracy                           0.87       242
   macro avg       0.88      0.87      0.87       242
weighted avg       0.88      0.87      0.87       242



### Testing

In [83]:
y_pred_test = lr_model.predict(x_test)

cnf_metrics = confusion_matrix(y_test,y_pred_test)
print("confusion metrics\n",cnf_metrics)
print("*"*20)
accuracy = accuracy_score(y_test,y_pred_test)
print("Accuracy\n",accuracy)
print("*"*20)
clf_report = classification_report(y_test,y_pred_test)
print("classification report\n",clf_report)

confusion metrics
 [[17 11]
 [ 2 31]]
********************
Accuracy
 0.7868852459016393
********************
classification report
               precision    recall  f1-score   support

           0       0.89      0.61      0.72        28
           1       0.74      0.94      0.83        33

    accuracy                           0.79        61
   macro avg       0.82      0.77      0.78        61
weighted avg       0.81      0.79      0.78        61



In [ ]:
Model                       Training accuracy      Testing accuracy       Precision        Recall 
DT_Hyperparamter                      90%                 73%                87%           92% 
DT_Pruning                            88%                 78%
RF_Hyper                              88%                 77%                89%           85%
RF_Without Hyper                      100                 78%                100           100
Adaboost_Without                      95%                 73%                94%           95%
Adaboost_Hyperpar                     86%                 73%                89%           78% 
KNN_hyperpara                         74%                 71%                73%           65%
Logistic                              87%                78%                 89%           61%

In [ ]:
#age	sex	cp	trestbps	chol	fbs	restecg	thalach	exang	oldpeak	slope	ca	thal	target

In [ ]:
project_data = {"columns":list(x.columns)}


In [ ]:
column_names = x.columns
test_array = np.zeros(x.shape[1])
test_array[0] = age
test_array[1] = sex
test_array[2] = cp
test_array[3] = trestbps
test_array[4] = chol
test_array[5] = fbs
test_array[6] = restecg
test_array[7] = thalach
test_array[8] = exang
test_array[9] = oldpeak
test_array[10] = slope
test_array[11] = ca
test_array[12] = thal

test_array

In [ ]:
with open("RF_CLF.pkl","wb") as f:
    pickle.dump(rf_clf1,f)